### PR TITLE
Create MANIFEST.in

### PR DESCRIPTION
**Pull request by ihleonard-c3**
Add include_package_data=True to setup.py

### CODE REVIEW

**Comment by ihleonard-c3** [comment]
> Oh why open then close this?

wrong target repo, my mistake

**Comment by okhat** [comment]
Haha okay then

**Comment by ihleonard-c3** [comment]
Besides, apparently that gets me a prize? :smile: 

image

**Comment by okhat** [comment]
Haha very cool! But the awards of contributing to colbert are hard to match!

**Pull request closed without merging**
