### PR TITLE
Make sure pids is in cpu when preparing variables for lookup in `strided_tensor.py`

### LINKED ISSUE #148: indices should be either on cpu or on the same device as the indexed tensor (cpu)
It happens when I run the intro.ipynb ,
```
results = searcher.search(query, k=3)
````
the output is 
```
RuntimeError                              Traceback (most recent call last)
Cell In[19], line 6
      3 print(f"#> {query}")
      5 # Find the top-3 passages for this query
----> 6 results = searcher.search(query, k=3)
      8 # Print out the top-k retrieved passages
      9 for passage_id, passage_rank, passage_score in zip(*results):

File ~/ColBERT/docs/../colbert/searcher.py:61, in Searcher.search(self, text, k, filter_fn)
     59 def search(self, text: str, k=10, filter_fn=None):
     60     Q = self.encode(text)
---> 61     return self.dense_search(Q, k, filter_fn=filter_fn)

File ~/ColBERT/docs/../colbert/searcher.py:108, in Searcher.dense_search(self, Q, k, filter_fn)
    105     if self.config.ndocs is None:
    106         self.configure(ndocs=max(k * 4, 4096))
--> 108 pids, scores = self.ranker.rank(self.config, Q, filter_fn=filter_fn)
    110 return pids[:k], list(range(1, k+1)), scores[:k]

File ~/ColBERT/docs/../colbert/search/index_storage.py:79, in IndexScorer.rank(self, config, Q, filter_fn)
     77 def rank(self, config, Q, filter_fn=None):
     78     with torch.inference_mode():
---> 79         pids, centroid_scores = self.retrieve(config, Q)
     81         if filter_fn is not None:
     82             pids = filter_fn(pids)

File ~/ColBERT/docs/../colbert/search/index_storage.py:69, in IndexScorer.retrieve(self, config, Q)
     67 def retrieve(self, config, Q):
     68     Q = Q[:, :config.query_maxlen]   # NOTE: Candidate generation uses only the query tokens
---> 69     embedding_ids, centroid_scores = self.generate_candidates(config, Q)
     71     return embedding_ids, centroid_scores
File ~/ColBERT/docs/../colbert/search/candidate_generation.py:55, in CandidateGeneration.generate_candidates(self, config, Q)
     52     Q = Q.cuda().half()
     53 assert Q.dim() == 2
---> 55 pids, centroid_scores = self.generate_candidate_pids(Q, ncells)
     57 sorter = pids.sort()
     58 pids = sorter.values

File ~/ColBERT/docs/../colbert/search/candidate_generation.py:34, in CandidateGeneration.generate_candidate_pids(self, Q, ncells)
     31 def generate_candidate_pids(self, Q, ncells):
     32     cells, scores = self.get_cells(Q, ncells)
---> 34     pids, cell_lengths = self.ivf.lookup(cells)
     35     if self.use_gpu:
     36         pids = pids.cuda()

File ~/ColBERT/docs/../colbert/search/strided_tensor.py:75, in StridedTensor.lookup(self, pids, output)
     74 def lookup(self, pids, output='packed'):
---> 75     pids, lengths, offsets = self._prepare_lookup(pids)
     77     if self.use_gpu:
     78         stride = lengths.max().item()

File ~/ColBERT/docs/../colbert/search/strided_tensor.py:67, in StridedTensor._prepare_lookup(self, pids)
     65     pids = pids.cuda()
     66 pids = pids.long()
---> 67 lengths = self.lengths[pids]
     68 if self.use_gpu:
     69     lengths = lengths.cuda()

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

seems like the device setting got mismatched and i overwrite the prepare_lookup func
```
def _prepare_lookup(self, pids):
        if isinstance(pids, list):
            pids = torch.tensor(pids)

        assert pids.dim() == 1

        if self.use_gpu:
            pids = pids.cuda()
        pids = pids.long()
        lengths = self.lengths[pids]
        if self.use_gpu:
            lengths = lengths.cuda()
        offsets = self.offsets[pids]

        return pids, lengths, offsets
```
another device mismatch happened

### PR DESCRIPTION
**Pull request by eugene-yang**
close #148

### CODE REVIEW

**Comment by eugene-yang** [comment]
@santhnm2 Is this solution raising other issues?

**Comment by santhnm2** [comment]
@

> @santhnm2 Is this solution raising other issues?

This PR does fix the issue but I'm testing whether the lengths and offsets in `strided_tensor_core.py` can be safely moved to the GPU without running out of memory - doing so could give a speedup (roughly 10% in my initial experiments).

**Comment by santhnm2** [comment]
@eugene-yang I will merge this PR in for now and put another one in if the faster solution ends up working - thanks for your help tracing this!

**Comment by eugene-yang** [comment]
@santhnm2 I don't think we can move the lengths and offsets into GPUs unless we are somehow slicing them. 
If I understand the code correctly, those are for all the passages in the collection, right?

**Comment by santhnm2** [comment]
The lengths and offsets have a fairly low memory overhead as these are simply one long per passage. So even at the scale of 150M passages, this amounts to only 1.2 GB for each of lengths and offsets.

**Pull request merged**
