### PR TITLE
2 new API endpoints to IndexUpdater: create_embs_and_doclens and update_searcher

### PR DESCRIPTION
**Pull request by jessiejuachon**
1. create_embs_and_doclens - Create embeddings and doclens for new  passages, with option to persist to disk.
2. update_searcher - Update the searcher with the said embeddings and doclens.

This is to support the following workflow:
1. To add new passages, call `create_embs_and_doclens` on the GPU. Set `persist` argument to True.
2. Pull the persisted embeddings and doclens files and upload to elsewhere.
3. Have another application call `update_searcher`, with the files from step 2 as input. This will allow to insert new embeddings into an index that had been loaded in memory.

### CODE REVIEW

**Comment by okhat** [comment]
This looks good to me, but I was not involved in building this component so I'm likely missing something. @santhnm2 and @narnix-gnos, do you have thoughts?

@jessiejuachon Do you want to think about adding handling for the workflow where the number of documents is too small or is grown too much for the current approach? I remember we had a rich discussion around that

**Comment by okhat** [comment]
Anyway, looks good to merge from my end

**Comment by jjuachon** [comment]
> This looks good to me, but I was not involved in building this component so I'm likely missing something. @santhnm2 and @narnix-gnos, do you have thoughts?
> 
> @jessiejuachon Do you want to think about adding handling for the workflow where the number of documents is too small or is grown too much for the current approach? I remember we had a rich discussion around that

Thanks! Will wait for @santhnm2 / @narnix-gnos . 

Yes, that is something that can be looked at after this merge request!

**Review by santhnm2 — APPROVED** [review]
LGTM, but are any changes required for this test? https://github.com/stanford-futuredata/ColBERT/blob/main/colbert/tests/index_updater_test.py

**Comment by jessiejuachon** [comment]
> LGTM, but are any changes required for this test? https://github.com/stanford-futuredata/ColBERT/blob/main/colbert/tests/index_updater_test.py

I believe there should be no change in the test. In this PR, there is no change in the code logic of the `add` function. The only change is instead of the `add` function containing all of its original code, it now calls 2 new functions: `create_embs_and_doclens` and `update_searcher`.

**Pull request merged**
