### PR TITLE
We use the colbertv1 for our model.

### PR DESCRIPTION
**Pull request by MarkLee131**
For reload, we modified the `eager_batcher.py` in the `training` folder. 
The command we used to train the model is:
```bash
CUDA_VISIBLE_DEVICES="0,1,2,3" python -m torch.distributed.launch --nproc_per_node=4 -m colbert.train --amp --doc_maxlen 512 --mask-punctuation --bsize 64 --accum 1 --triples data/train_data.tsv --root commits_exp --experiment commits_train_cont --similarity l2 --run test.l2 --resume --checkpoint commits_exp/commits_train/train.py/test.l2/checkpoints/colbert-200000.dnn
```
But in the checkpoint folder, there exists a model file named `colbert.dnn`, not sure its usage.
@Jian, help to review it, plz.
image

### CODE REVIEW

**Comment by okhat** [comment]
colbert.dnn is the latest checkpoint

**Comment by MarkLee131** [comment]
Hello @okhat,

Thank you for your swift and helpful response earlier. We're currently using colbertv1 for our project. After facing a server issue, we attempted to reload and continue training the model using the `-resume -checkpoint (our checkpoint path)` command. However, we observed significantly increased memory consumption compared to our initial training, even though other arguments remained unchanged.

To address this, we made modifications to `eager_batcher.py`. Would you be able to review our changes within it and confirm if they're appropriate? Any guidance or feedback would be greatly appreciated.

Thanks in advance!

**Comment by okhat** [comment]
Sure but why close the issue?

**Comment by okhat** [comment]
ahh I see, so this isn't meant for merging, right?

**Comment by MarkLee131** [comment]
yes! Sry about it. Maybe a new PR would be better after I reorganize the changed files on my own later.

**Pull request closed without merging**
