### PR TITLE
Changes discussed in #2

### PR DESCRIPTION
**Pull request by cmacdonald**
Changes:
 - added .gitignore
 - python 3.6 support for contextmanagers
 - use requirements.txt in setup.pt
 - added __init__.py files to make them valid modules

You may want to refactor the 2x nullcontextmanager into a single location
Suggest squash merge.

### CODE REVIEW

**Comment by cmacdonald** [comment]
Hi @okhat - is there anything needed to get this merged? I can provide a patch for #10, but it would build upon this.

**Comment by okhat** [comment]
Hi Craig,

I'm sorry for the delayed response here; it's been a hectic few weeks.

I think my main concern is that the pip installation often incorrectly sets up faiss, so I wanted to think more about this. Conda seems to work more reliably.

One way to deal with this (like this PR, I think?) is to keep faiss out of the pip requirements altogether. But in practice e2e retrieval is essential to our recommended use of ColBERT.

**Comment by cmacdonald** [comment]
>I think my main concern is that the pip installation often incorrectly sets up faiss, so I wanted to think more about this. Conda seems to work more reliably.

Yes, the FAISS team confirmed this - see https://github.com/facebookresearch/faiss/issues/1545
Not sure why this worked sufficiently on Colab.

How about the other changes?

**Comment by okhat** [comment]
I think the other changes are py36 support (nullcontext changes) and adding init/gitignore. I think these are good to merge.

What about the requirements/pip aspect? Would it work for you to clarify the conda requirements and instructions, and otherwise remove the pip-related material?

**Comment by cmacdonald** [comment]
Yes, happy with that. Do you want a new PR?

**Comment by okhat** [comment]
No, this PR works for that. Will merge it today (Pacific time).

Many thanks, Craig!

**Comment by okhat** [comment]
Merged into v0.2 in #15. Thanks Craig!

Will add some instructions in v0.2 in the coming days.

**Pull request merged**
