### PR TITLE
support checkpoints from HTTP locations

### PR DESCRIPTION
**Pull request by cmacdonald**

### CODE REVIEW

**Comment by okhat** [comment]
Thanks Craig! I've not used `torch.hub.load_state_dict_from_url` before but the name suggests it loads only a state_dict and not the full checkpoint, which often has other metadata. Is this right?

**Comment by cmacdonald** [comment]
Sorry, I'm not sure. It appeared to work fine for us in these demo notebooks:
https://github.com/terrierteam/pyterrier_colbert/blob/main/colbert_text_and_explain.ipynb
https://github.com/terrierteam/pyterrier_colbert/blob/main/vaswani.ipynb
(direct open in colab links at https://github.com/terrierteam/pyterrier_colbert#demos)

I can try to verify versus using the checkpoint locally.

**Comment by okhat** [comment]
Just tested this with one of our checkpoints.

With torch 1.6.0, I get:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[...]/site-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile
```

It appears (though I am not sure) that this was fixed in 1.6.1: https://github.com/pytorch/pytorch/issues/42239

Will have to test with >= 1.6.1 and if all is good, looks like it's ready to merge

**Comment by okhat** [comment]
I think this is good. I will just set map_location = cpu.

**Comment by cmacdonald** [comment]
Thanks Omar.

**Pull request merged**
