### PR TITLE
Add API to rerank a given list of pids per query

### PR DESCRIPTION
**Pull request by santhnm2**

### CODE REVIEW

**Comment by santhnm2** [comment]
CC @detaos @jessiejuachon this PR makes a minor change to the `filter_fn` API so you may want to double check it doesn't break anything

**Comment by okhat** [comment]
Maybe we call it pids for consistency with rest of code and also so it’s super clear it’s ids not strings

**Comment by okhat** [comment]
For search all, should it be a list of lists?

**Comment by santhnm2** [comment]
> For search all, should it be a list of lists?

It can be, right now it's a dict keyed by qid but either is fine

**Comment by okhat** [comment]
Ah ok that’s nicer! But maybe the field name should be qid2pids

**Comment by santhnm2** [comment]
> Ah ok that’s nicer! But maybe the field name should be qid2pids

I can make it `rerank_pids` in the `search` case and `qid_to_rerank_pids` in the `search_all` case?

**Comment by okhat** [comment]
Sure. Or just pids and qid2pids. I like those more, rerank is redundant

**Pull request merged**
